# Generated by Django 4.2.22 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_migrate_list_layout_to_kanban"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bug_found_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="issue",
            name="bug_found_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="issue",
            name="affected_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="draftissue",
            name="bug_found_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="draftissue",
            name="affected_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="issueversion",
            name="bug_found_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="issueversion",
            name="affected_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
